name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: testing, UPSTREAM_WORKSPACE: 'uavcan_ros_bridge.rosinstall -uavcan_ros_bridge', ADDITIONAL_DEBS: 'python'}
          - {ROS_DISTRO: noetic, ROS_REPO: main, UPSTREAM_WORKSPACE: 'uavcan_ros_bridge.rosinstall -uavcan_ros_bridge', ADDITIONAL_DEBS: 'python'}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
